
cqt:
  min_freq: 40                      # <= Minimum CQT frequency in Hz
  samples_per_octave: 12            # <= Number of cqt samples per octave at each time point
  octaves: 6                        # <= Number of octaves in CQT analysis, starting at min_freq
  hop: 0.0039                       # <= Hop in seconds between successive CQT windows in on example
  num_windows: 1024                 # <= Number of consecutive CQT windows per example

beat_cqt_triplet:
  beats_after: 512                    # <= Number of beats ahead of a randomly selected time point to form cqt segment
  beats_before: 512                   # <= Number of beats behind a randomly selected time point to form cqt segment
  probability_before_positive: 0.5  # <= Probability that the positive triplet example is before the anchor (or 1.0 minus the probability it is after)
  min_offset_positive: 1024            # <= Minimum offset in beats of the center of the positive triplet example from the center of the anchor
  max_offset_positive: 2048           # <= Maximum offset in beats of the center of the positive triplet example from the center of the anchor
  probability_before_negative: 0.5  # <= Probability that the negative triplet example is before the anchor (or 1.0 minus the probability it is after)
  min_offset_negative: 4096           # <= Minimum offset in beats of the center of the negative triplet example from the center of the anchor
  max_offset_negative: 999999999999 # <= Maximum offset in beats of the center of the negative triplet example from the center of the anchor

beat_track_config:
  beatgrid_min_bpm: 70              # <= Minimum BPM parameter for the beatgrid tracker
  beatgrid_max_bpm: 200             # <= Maximum BPM parameter for the beatgrid tracker

beat_cqt_triplet_sampler:
  probability_same_file: 0.8        # <= Probability that the negative sample in the triplet is from the same file or different file to the anchor
  batch_size: 10                    # <= Total number of triplets to produce per batch